const MovieTypes  = {
    "FETCH_MOVIES_PENDING":"FETCH_MOVIES_PENDING",
    "FETCH_MOVIES_SUCCESS":"FETCH_MOVIES_SUCCESS",
    "FETCH_MOVIES_ERROR":"FETCH_MOVIES_ERROR",
    "DELETE_MOVIE":"DELETE_MOVIE",
    "UPDATE_MOVIE":"UPDATE_MOVIE"
}

export default MovieTypes;